### ISSUE TITLE
Create the Renderer

### ISSUE THREAD

**Issue by trezy** [trezy-studios/js13k-2020#1]
**Acceptance Criteria**

- [x] The renderer can render multiple layers
  - [x] Background
  - [x] Grid
  - [x] Entities
- [x] The renderer maintains the game's aspect ratio

**Comment by IanSSenne** [comment]
@trezy can you give an example of when this would be false? ` ``The renderer maintains the game's aspect ratio```

**Comment by trezy** [comment]
@IanSSenne Sure. In the case that the user resizes the browser window, the game should adjust to fit within the new browser window size. The game should be able to do this without ruining the game's aspect ratio.

**Example**
The game is 500px x 500px. This gives the game a 1x1 aspect ratio. The browser window is also sized to 500px x 500px.
The user stretches their browser window horizontally until it is 1000px wide.
The game adjusts itself because of the browser window resize. The game is now 1000px x 500px. It now has an aspect ratio of 2x1.
The browser has been resized, but the game's aspect ratio has not been maintained.

**Comment by IanSSenne** [comment]
isnt that just not resizing the canvas?

**Comment by trezy** [comment]
I added a second scenario to hopefully clear up what the game should *and* should not do in regards to resizing itself and maintaining its aspect ratio.
